/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Child {
  'id' : bigint,
  'name' : string,
  'balanceCents' : bigint,
}
export interface Chore {
  'id' : bigint,
  'name' : string,
  'amountCents' : bigint,
  'isActive' : boolean,
  'frequency' : ChoreFrequency,
}
export interface ChoreCompletion {
  'id' : bigint,
  'status' : ChoreStatus,
  'submittedAt' : bigint,
  'childId' : bigint,
  'choreId' : bigint,
}
export type ChoreFrequency = { 'unlimitedDaily' : null } |
  { 'oncePerWeek' : null } |
  { 'oncePerDay' : null };
export type ChoreStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ChoreWithAvailability {
  'chore' : Chore,
  'canSubmit' : boolean,
  'reason' : [] | [string],
}
export interface Transaction {
  'id' : bigint,
  'note' : string,
  'createdAt' : bigint,
  'amountCents' : bigint,
  'childId' : bigint,
  'txType' : TransactionType,
}
export type TransactionType = { 'deduction' : null } |
  { 'credit' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChild' : ActorMethod<[string], bigint>,
  'addChore' : ActorMethod<[string, bigint, ChoreFrequency, boolean], bigint>,
  'approveCompletion' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignChoreToChildren' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'deductMoney' : ActorMethod<[bigint, bigint, string], boolean>,
  'getAllChoreAssignments' : ActorMethod<[], Array<[bigint, Array<bigint>]>>,
  'getAllChores' : ActorMethod<[], Array<Chore>>,
  'getAllCompletions' : ActorMethod<[], Array<ChoreCompletion>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChildCompletions' : ActorMethod<[bigint], Array<ChoreCompletion>>,
  'getChildInfo' : ActorMethod<[bigint], [] | [Child]>,
  'getChildTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getChildren' : ActorMethod<[], Array<Child>>,
  'getChoreAssignments' : ActorMethod<[bigint], Array<bigint>>,
  'getChoresForChild' : ActorMethod<[bigint], Array<ChoreWithAvailability>>,
  'getPendingCompletions' : ActorMethod<[], Array<ChoreCompletion>>,
  'getTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectCompletion' : ActorMethod<[bigint], boolean>,
  'removeChild' : ActorMethod<[bigint], boolean>,
  'removeChore' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitChoreCompletion' : ActorMethod<[bigint, bigint], boolean>,
  'updateChildName' : ActorMethod<[bigint, string], boolean>,
  'updateChore' : ActorMethod<
    [bigint, string, bigint, ChoreFrequency, boolean],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];