/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChoreFrequency = IDL.Variant({
  'unlimitedDaily' : IDL.Null,
  'oncePerWeek' : IDL.Null,
  'oncePerDay' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Chore = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'amountCents' : IDL.Int,
  'isActive' : IDL.Bool,
  'frequency' : ChoreFrequency,
});
export const ChoreStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ChoreCompletion = IDL.Record({
  'id' : IDL.Nat,
  'status' : ChoreStatus,
  'submittedAt' : IDL.Int,
  'childId' : IDL.Nat,
  'choreId' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'deduction' : IDL.Null,
  'credit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'amountCents' : IDL.Int,
  'childId' : IDL.Nat,
  'txType' : TransactionType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Child = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'balanceCents' : IDL.Int,
});
export const ChoreWithAvailability = IDL.Record({
  'chore' : Chore,
  'canSubmit' : IDL.Bool,
  'reason' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChild' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addChore' : IDL.Func(
      [IDL.Text, IDL.Int, ChoreFrequency, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'approveCompletion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignChoreToChildren' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'deductMoney' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Bool], []),
  'getAllChoreAssignments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Nat)))],
      ['query'],
    ),
  'getAllChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
  'getAllCompletions' : IDL.Func([], [IDL.Vec(ChoreCompletion)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChildCompletions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ChoreCompletion)],
      ['query'],
    ),
  'getChildInfo' : IDL.Func([IDL.Nat], [IDL.Opt(Child)], ['query']),
  'getChildTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
  'getChildrenPublic' : IDL.Func([], [IDL.Vec(Child)], ['query']),
  'getChoreAssignments' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getChoresForChild' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ChoreWithAvailability)],
      ['query'],
    ),
  'getPendingCompletions' : IDL.Func([], [IDL.Vec(ChoreCompletion)], ['query']),
  'getTransactions' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectCompletion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeChild' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeChore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitChoreCompletion' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateChildName' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateChore' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int, ChoreFrequency, IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChoreFrequency = IDL.Variant({
    'unlimitedDaily' : IDL.Null,
    'oncePerWeek' : IDL.Null,
    'oncePerDay' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Chore = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'amountCents' : IDL.Int,
    'isActive' : IDL.Bool,
    'frequency' : ChoreFrequency,
  });
  const ChoreStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ChoreCompletion = IDL.Record({
    'id' : IDL.Nat,
    'status' : ChoreStatus,
    'submittedAt' : IDL.Int,
    'childId' : IDL.Nat,
    'choreId' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'deduction' : IDL.Null,
    'credit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'amountCents' : IDL.Int,
    'childId' : IDL.Nat,
    'txType' : TransactionType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Child = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'balanceCents' : IDL.Int,
  });
  const ChoreWithAvailability = IDL.Record({
    'chore' : Chore,
    'canSubmit' : IDL.Bool,
    'reason' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChild' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addChore' : IDL.Func(
        [IDL.Text, IDL.Int, ChoreFrequency, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'approveCompletion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignChoreToChildren' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'deductMoney' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Bool], []),
    'getAllChoreAssignments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Nat)))],
        ['query'],
      ),
    'getAllChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
    'getAllCompletions' : IDL.Func([], [IDL.Vec(ChoreCompletion)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChildCompletions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChoreCompletion)],
        ['query'],
      ),
    'getChildInfo' : IDL.Func([IDL.Nat], [IDL.Opt(Child)], ['query']),
    'getChildTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
    'getChildrenPublic' : IDL.Func([], [IDL.Vec(Child)], ['query']),
    'getChoreAssignments' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getChoresForChild' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChoreWithAvailability)],
        ['query'],
      ),
    'getPendingCompletions' : IDL.Func(
        [],
        [IDL.Vec(ChoreCompletion)],
        ['query'],
      ),
    'getTransactions' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectCompletion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeChild' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeChore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitChoreCompletion' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'updateChildName' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateChore' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, ChoreFrequency, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };