/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Chore {
    id: bigint;
    name: string;
    amountCents: bigint;
    isActive: boolean;
    frequency: ChoreFrequency;
}
export interface ChoreCompletion {
    id: bigint;
    status: ChoreStatus;
    submittedAt: bigint;
    childId: bigint;
    choreId: bigint;
}
export interface Child {
    id: bigint;
    name: string;
    balanceCents: bigint;
}
export interface ChoreWithAvailability {
    chore: Chore;
    canSubmit: boolean;
    reason?: string;
}
export interface UserProfile {
    name: string;
}
export interface Transaction {
    id: bigint;
    note: string;
    createdAt: bigint;
    amountCents: bigint;
    childId: bigint;
    txType: TransactionType;
}
export enum ChoreFrequency {
    unlimitedDaily = "unlimitedDaily",
    oncePerWeek = "oncePerWeek",
    oncePerDay = "oncePerDay"
}
export enum ChoreStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TransactionType {
    deduction = "deduction",
    credit = "credit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChild(name: string): Promise<bigint>;
    addChore(name: string, amountCents: bigint, frequency: ChoreFrequency, isActive: boolean): Promise<bigint>;
    approveCompletion(completionId: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignChoreToChildren(choreId: bigint, childIds: Array<bigint>): Promise<void>;
    deductMoney(childId: bigint, amountCents: bigint, note: string): Promise<boolean>;
    getAllChoreAssignments(): Promise<Array<[bigint, Array<bigint>]>>;
    getAllChores(): Promise<Array<Chore>>;
    getAllCompletions(): Promise<Array<ChoreCompletion>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChildCompletions(childId: bigint): Promise<Array<ChoreCompletion>>;
    getChildInfo(childId: bigint): Promise<Child | null>;
    getChildTransactions(childId: bigint): Promise<Array<Transaction>>;
    getChildren(): Promise<Array<Child>>;
    getChildrenPublic(): Promise<Array<Child>>;
    getChoreAssignments(choreId: bigint): Promise<Array<bigint>>;
    getChoresForChild(childId: bigint): Promise<Array<ChoreWithAvailability>>;
    getPendingCompletions(): Promise<Array<ChoreCompletion>>;
    getTransactions(childId: bigint): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectCompletion(completionId: bigint): Promise<boolean>;
    removeChild(childId: bigint): Promise<boolean>;
    removeChore(choreId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitChoreCompletion(childId: bigint, choreId: bigint): Promise<boolean>;
    updateChildName(childId: bigint, name: string): Promise<boolean>;
    updateChore(choreId: bigint, name: string, amountCents: bigint, frequency: ChoreFrequency, isActive: boolean): Promise<boolean>;
}
import type { Child as _Child, Chore as _Chore, ChoreCompletion as _ChoreCompletion, ChoreFrequency as _ChoreFrequency, ChoreStatus as _ChoreStatus, ChoreWithAvailability as _ChoreWithAvailability, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChild(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChild(arg0);
            return result;
        }
    }
    async addChore(arg0: string, arg1: bigint, arg2: ChoreFrequency, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChore(arg0, arg1, to_candid_ChoreFrequency_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChore(arg0, arg1, to_candid_ChoreFrequency_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async approveCompletion(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCompletion(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignChoreToChildren(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignChoreToChildren(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignChoreToChildren(arg0, arg1);
            return result;
        }
    }
    async deductMoney(arg0: bigint, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deductMoney(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductMoney(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllChoreAssignments(): Promise<Array<[bigint, Array<bigint>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChoreAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChoreAssignments();
            return result;
        }
    }
    async getAllChores(): Promise<Array<Chore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChores();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChores();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCompletions(): Promise<Array<ChoreCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompletions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompletions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildCompletions(arg0: bigint): Promise<Array<ChoreCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildCompletions(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildCompletions(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildInfo(arg0: bigint): Promise<Child | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildInfo(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildInfo(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildTransactions(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildTransactions(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildren(): Promise<Array<Child>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildren();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildren();
            return result;
        }
    }
    async getChildrenPublic(): Promise<Array<Child>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildrenPublic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildrenPublic();
            return result;
        }
    }
    async getChoreAssignments(arg0: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChoreAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChoreAssignments(arg0);
            return result;
        }
    }
    async getChoresForChild(arg0: bigint): Promise<Array<ChoreWithAvailability>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChoresForChild(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChoresForChild(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingCompletions(): Promise<Array<ChoreCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCompletions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCompletions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectCompletion(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCompletion(arg0);
            return result;
        }
    }
    async removeChild(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeChild(arg0);
            return result;
        }
    }
    async removeChore(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeChore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeChore(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitChoreCompletion(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitChoreCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitChoreCompletion(arg0, arg1);
            return result;
        }
    }
    async updateChildName(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChildName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChildName(arg0, arg1);
            return result;
        }
    }
    async updateChore(arg0: bigint, arg1: string, arg2: bigint, arg3: ChoreFrequency, arg4: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChore(arg0, arg1, arg2, to_candid_ChoreFrequency_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChore(arg0, arg1, arg2, to_candid_ChoreFrequency_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_ChoreCompletion_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChoreCompletion): ChoreCompletion {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ChoreFrequency_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChoreFrequency): ChoreFrequency {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ChoreStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChoreStatus): ChoreStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ChoreWithAvailability_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChoreWithAvailability): ChoreWithAvailability {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Chore_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chore): Chore {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Child]): Child | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ChoreStatus;
    submittedAt: bigint;
    childId: bigint;
    choreId: bigint;
}): {
    id: bigint;
    status: ChoreStatus;
    submittedAt: bigint;
    childId: bigint;
    choreId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ChoreStatus_n13(_uploadFile, _downloadFile, value.status),
        submittedAt: value.submittedAt,
        childId: value.childId,
        choreId: value.choreId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    note: string;
    createdAt: bigint;
    amountCents: bigint;
    childId: bigint;
    txType: _TransactionType;
}): {
    id: bigint;
    note: string;
    createdAt: bigint;
    amountCents: bigint;
    childId: bigint;
    txType: TransactionType;
} {
    return {
        id: value.id,
        note: value.note,
        createdAt: value.createdAt,
        amountCents: value.amountCents,
        childId: value.childId,
        txType: from_candid_TransactionType_n18(_uploadFile, _downloadFile, value.txType)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chore: _Chore;
    canSubmit: boolean;
    reason: [] | [string];
}): {
    chore: Chore;
    canSubmit: boolean;
    reason?: string;
} {
    return {
        chore: from_candid_Chore_n6(_uploadFile, _downloadFile, value.chore),
        canSubmit: value.canSubmit,
        reason: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.reason))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    amountCents: bigint;
    isActive: boolean;
    frequency: _ChoreFrequency;
}): {
    id: bigint;
    name: string;
    amountCents: bigint;
    isActive: boolean;
    frequency: ChoreFrequency;
} {
    return {
        id: value.id,
        name: value.name,
        amountCents: value.amountCents,
        isActive: value.isActive,
        frequency: from_candid_ChoreFrequency_n8(_uploadFile, _downloadFile, value.frequency)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ChoreStatus {
    return "pending" in value ? ChoreStatus.pending : "approved" in value ? ChoreStatus.approved : "rejected" in value ? ChoreStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deduction: null;
} | {
    credit: null;
}): TransactionType {
    return "deduction" in value ? TransactionType.deduction : "credit" in value ? TransactionType.credit : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlimitedDaily: null;
} | {
    oncePerWeek: null;
} | {
    oncePerDay: null;
}): ChoreFrequency {
    return "unlimitedDaily" in value ? ChoreFrequency.unlimitedDaily : "oncePerWeek" in value ? ChoreFrequency.oncePerWeek : "oncePerDay" in value ? ChoreFrequency.oncePerDay : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChoreCompletion>): Array<ChoreCompletion> {
    return value.map((x)=>from_candid_ChoreCompletion_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChoreWithAvailability>): Array<ChoreWithAvailability> {
    return value.map((x)=>from_candid_ChoreWithAvailability_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chore>): Array<Chore> {
    return value.map((x)=>from_candid_Chore_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ChoreFrequency_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChoreFrequency): _ChoreFrequency {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChoreFrequency): {
    unlimitedDaily: null;
} | {
    oncePerWeek: null;
} | {
    oncePerDay: null;
} {
    return value == ChoreFrequency.unlimitedDaily ? {
        unlimitedDaily: null
    } : value == ChoreFrequency.oncePerWeek ? {
        oncePerWeek: null
    } : value == ChoreFrequency.oncePerDay ? {
        oncePerDay: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
